---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./__tests__/*.spec.ts"
postMerge:
  pattern:
    - "./__tests__/*.spec.ts"
postRun:
     command:
        - yarn --version
version: 1.0
